"""
Curated Y Combinator Startup Opportunities Dataset
===================================================
Frontier startups across Agentic AI, Developer Platforms, Distributed Systems,
Robotics, Fintech, and Modern Infrastructure.
"""

from typing import List, Dict, Any

SAMPLE_YC_JOBS: List[Dict[str, Any]] = [
    {
        "id": "yc-job-001",
        "title": "Founding AI / Agentic Systems Engineer",
        "company": "Cognition Forge",
        "company_url": "https://www.ycombinator.com/companies/cognition-forge",
        "batch": "YC W25",
        "stage": "Seed ($4.5M)",
        "team_size": "6 engineers",
        "location": "San Francisco, CA",
        "work_type": "Hybrid (SF / Remote OK)",
        "salary_str": "$170,000 - $240,000",
        "salary_min": 170000,
        "salary_max": 240000,
        "equity": "1.0% - 2.5%",
        "experience_level": "Senior (4+ years)",
        "skills": ["Python", "PyTorch", "LLMs", "RAG", "FastAPI", "VectorDB", "Docker"],
        "description": "Building autonomous AI agents that debug, refactor, and write multi-repo production codebases. Looking for a founding engineer who has trained or fine-tuned LLMs and built low-latency inference pipelines.",
        "founder_note": "Founded by ex-Google Brain & Stanford AI researchers. Backed by Founders Fund and YC.",
        "visa_sponsorship": True,
        "culture_tags": ["High Autonomy", "Frontier AI", "Speed of Shipping"],
        "url": "https://www.ycombinator.com/jobs/ai-agentic-engineer-cognition",
        "posted_date": "2 hours ago"
    },
    {
        "id": "yc-job-002",
        "title": "Lead Full Stack Engineer (Python & React)",
        "company": "HyperFlow Data",
        "company_url": "https://www.ycombinator.com/companies/hyperflow",
        "batch": "YC S24",
        "stage": "Series A ($12M)",
        "team_size": "14 people",
        "location": "Remote (Worldwide)",
        "work_type": "Remote",
        "salary_str": "$140,000 - $195,000",
        "salary_min": 140000,
        "salary_max": 195000,
        "equity": "0.4% - 1.0%",
        "experience_level": "Mid-Senior (3+ years)",
        "skills": ["Python", "React", "TypeScript", "Next.js", "PostgreSQL", "TailwindCSS", "FastAPI"],
        "description": "HyperFlow is the real-time data automation backbone for fast-growing SaaS startups. You will lead full-stack product development, architecting high-throughput REST/GraphQL APIs in Python and craft-focused React interfaces.",
        "founder_note": "Fast revenue growth ($2M ARR). Remote-first engineering team across 4 continents.",
        "visa_sponsorship": False,
        "culture_tags": ["Remote-First", "High Craft", "Design-Driven"],
        "url": "https://www.ycombinator.com/jobs/lead-fullstack-hyperflow",
        "posted_date": "1 day ago"
    },
    {
        "id": "yc-job-003",
        "title": "Staff Distributed Systems Engineer (Rust / Go)",
        "company": "Aura Cloud",
        "company_url": "https://www.ycombinator.com/companies/aura-cloud",
        "batch": "YC W24",
        "stage": "Series A ($18M)",
        "team_size": "22 people",
        "location": "New York, NY",
        "work_type": "Onsite",
        "salary_str": "$190,000 - $260,000",
        "salary_min": 190000,
        "salary_max": 260000,
        "equity": "0.5% - 1.8%",
        "experience_level": "Staff / Principal (5+ years)",
        "skills": ["Rust", "Go", "Distributed Systems", "Kubernetes", "gRPC", "Kafka", "Linux"],
        "description": "Aura Cloud is reimagining edge compute infrastructure for AI workloads. Seeking a distributed systems veteran to architect high-throughput messaging pipelines processing billions of events daily.",
        "founder_note": "Backed by Sequoia and YC. Engineering leaders from Cloudflare and AWS.",
        "visa_sponsorship": True,
        "culture_tags": ["Deep Tech", "Zero-Latency", "Systems Craft"],
        "url": "https://www.ycombinator.com/jobs/staff-distributed-aura",
        "posted_date": "3 days ago"
    },
    {
        "id": "yc-job-004",
        "title": "Senior Applied NLP & Prompt Research Engineer",
        "company": "Chatterbox Health",
        "company_url": "https://www.ycombinator.com/companies/chatterbox-health",
        "batch": "YC W24",
        "stage": "Seed ($3.8M)",
        "team_size": "8 people",
        "location": "Remote (US / Europe)",
        "work_type": "Remote",
        "salary_str": "$150,000 - $200,000",
        "salary_min": 150000,
        "salary_max": 200000,
        "equity": "0.6% - 1.5%",
        "experience_level": "Senior (3+ years)",
        "skills": ["Python", "AI", "NLP", "LangChain", "OpenAI", "FastAPI", "VectorDB", "LlamaIndex"],
        "description": "Building clinical-grade AI scribes and patient follow-up conversational agents. We need an Applied AI engineer proficient with LangChain/LlamaIndex, evaluation frameworks, and HIPAA-compliant Python backends.",
        "founder_note": "Deployed in 40+ medical clinics across North America.",
        "visa_sponsorship": True,
        "culture_tags": ["HealthTech", "AI Agents", "High Impact"],
        "url": "https://www.ycombinator.com/jobs/applied-nlp-chatterbox",
        "posted_date": "5 hours ago"
    },
    {
        "id": "yc-job-005",
        "title": "Founding Frontend Architect (Design Systems)",
        "company": "Vellum Studio",
        "company_url": "https://www.ycombinator.com/companies/vellum-studio",
        "batch": "YC S24",
        "stage": "Seed ($3.2M)",
        "team_size": "5 people",
        "location": "San Francisco, CA",
        "work_type": "Hybrid",
        "salary_str": "$135,000 - $175,000",
        "salary_min": 135000,
        "salary_max": 175000,
        "equity": "1.0% - 2.5%",
        "experience_level": "Senior (4+ years)",
        "skills": ["Frontend", "React", "TypeScript", "Next.js", "UI/UX", "TailwindCSS", "Figma", "CSS"],
        "description": "Linear-grade interface engineering for an AI-native creative canvas. You will build pixel-perfect interfaces, multi-threaded canvas rendering, and accessible design system components.",
        "founder_note": "Designers and engineers obsessed with 60fps micro-interactions.",
        "visa_sponsorship": False,
        "culture_tags": ["Linear Aesthetic", "Craft Obsessed", "High Bar"],
        "url": "https://www.ycombinator.com/jobs/frontend-architect-vellum",
        "posted_date": "Just now"
    },
    {
        "id": "yc-job-006",
        "title": "Lead Generative AI Research Scientist",
        "company": "Synthetica AI",
        "company_url": "https://www.ycombinator.com/companies/synthetica-ai",
        "batch": "YC W24",
        "stage": "Series A ($20M)",
        "team_size": "18 people",
        "location": "San Francisco, CA",
        "work_type": "Onsite",
        "salary_str": "$200,000 - $280,000",
        "salary_min": 200000,
        "salary_max": 280000,
        "equity": "0.75% - 2.0%",
        "experience_level": "Staff / Lead (5+ years)",
        "skills": ["Python", "AI", "PyTorch", "Diffusion Models", "Transformers", "CUDA", "C++"],
        "description": "Synthetica AI develops multi-modal generative models for creative professionals. We are hiring a research engineer to push the boundaries of diffusion architectures and low-latency inference.",
        "founder_note": "Over 500,000 creators use Synthetica models daily.",
        "visa_sponsorship": True,
        "culture_tags": ["Frontier Research", "Model Training", "Compute Heavy"],
        "url": "https://www.ycombinator.com/jobs/lead-genai-synthetica",
        "posted_date": "2 days ago"
    },
    {
        "id": "yc-job-007",
        "title": "Founding Cloud Platform & DevOps Engineer",
        "company": "KubeMesh",
        "company_url": "https://www.ycombinator.com/companies/kubemesh",
        "batch": "YC W23",
        "stage": "Seed ($4.0M)",
        "team_size": "9 people",
        "location": "Remote (US / Canada)",
        "work_type": "Remote",
        "salary_str": "$145,000 - $190,000",
        "salary_min": 145000,
        "salary_max": 190000,
        "equity": "0.5% - 1.2%",
        "experience_level": "Senior (4+ years)",
        "skills": ["DevOps", "Kubernetes", "Terraform", "AWS", "CI/CD", "Python", "Go", "Linux"],
        "description": "Automated multi-cloud cluster orchestration for AI model hosting. Manage Kubernetes clusters across AWS and GCP, build GitOps pipelines, and minimize p99 latency.",
        "founder_note": "Ex-Stripe and HashiCorp platform builders.",
        "visa_sponsorship": False,
        "culture_tags": ["Infra as Code", "Reliability", "Async Culture"],
        "url": "https://www.ycombinator.com/jobs/founding-devops-kubemesh",
        "posted_date": "4 days ago"
    },
    {
        "id": "yc-job-008",
        "title": "Core Database Engine Engineer (Rust / C++)",
        "company": "ZeroLatency DB",
        "company_url": "https://www.ycombinator.com/companies/zerolatency-db",
        "batch": "YC S24",
        "stage": "Seed ($5.0M)",
        "team_size": "7 people",
        "location": "San Francisco, CA",
        "work_type": "Hybrid",
        "salary_str": "$180,000 - $250,000",
        "salary_min": 180000,
        "salary_max": 250000,
        "equity": "1.2% - 3.0%",
        "experience_level": "Senior (4+ years)",
        "skills": ["Rust", "C++", "Database Internals", "SIMD", "Concurrency", "Linux"],
        "description": "Building the world's fastest in-memory vector database from scratch. You will work on lock-free data structures, SIMD vectorization, and NVMe-tiering architectures.",
        "founder_note": "Backed by Elad Gil, Nat Friedman, and YC.",
        "visa_sponsorship": True,
        "culture_tags": ["Hardcore Systems", "C++ to Rust", "Benchmarking"],
        "url": "https://www.ycombinator.com/jobs/core-db-zerolatency",
        "posted_date": "1 day ago"
    },
    {
        "id": "yc-job-009",
        "title": "Senior Data & Analytics Platform Engineer",
        "company": "MetricFlow",
        "company_url": "https://www.ycombinator.com/companies/metricflow",
        "batch": "YC S23",
        "stage": "Series A ($14M)",
        "team_size": "16 people",
        "location": "Remote (Worldwide)",
        "work_type": "Remote",
        "salary_str": "$135,000 - $180,000",
        "salary_min": 135000,
        "salary_max": 180000,
        "equity": "0.3% - 0.8%",
        "experience_level": "Mid-Senior (3+ years)",
        "skills": ["Python", "SQL", "Snowflake", "dbt", "FastAPI", "Data Engineering", "PostgreSQL"],
        "description": "Build modern data transformation layers and real-time behavioral analytics pipelines. Looking for a pragmatic data engineer proficient in Python, SQL, and event-driven streaming.",
        "founder_note": "Over 200 high-growth YC companies rely on MetricFlow for analytics.",
        "visa_sponsorship": False,
        "culture_tags": ["Data Obsessed", "Remote", "Customer Driven"],
        "url": "https://www.ycombinator.com/jobs/senior-data-metricflow",
        "posted_date": "3 days ago"
    },
    {
        "id": "yc-job-010",
        "title": "Founding Robotics Perception Engineer",
        "company": "Dexter Robotics",
        "company_url": "https://www.ycombinator.com/companies/dexter-robotics",
        "batch": "YC W25",
        "stage": "Seed ($6.0M)",
        "team_size": "8 people",
        "location": "San Francisco, CA",
        "work_type": "Onsite",
        "salary_str": "$175,000 - $235,000",
        "salary_min": 175000,
        "salary_max": 235000,
        "equity": "1.0% - 2.5%",
        "experience_level": "Senior (3+ years)",
        "skills": ["Python", "C++", "PyTorch", "Computer Vision", "ROS2", "Robotics", "CUDA"],
        "description": "Developing humanoid robotic hands and vision-language-action (VLA) manipulation policies. Seeking a perception engineer to fuse real-time RGB-D camera feeds with spatial policy networks.",
        "founder_note": "Spun out of UC Berkeley Robotics lab.",
        "visa_sponsorship": True,
        "culture_tags": ["Hardware + AI", "Lab Environment", "Next Frontier"],
        "url": "https://www.ycombinator.com/jobs/robotics-perception-dexter",
        "posted_date": "6 hours ago"
    },
    {
        "id": "yc-job-011",
        "title": "Senior Security & Privacy Engineer (Fintech)",
        "company": "VaultLayer",
        "company_url": "https://www.ycombinator.com/companies/vaultlayer",
        "batch": "YC W23",
        "stage": "Series A ($16M)",
        "team_size": "20 people",
        "location": "New York, NY",
        "work_type": "Hybrid",
        "salary_str": "$170,000 - $225,000",
        "salary_min": 170000,
        "salary_max": 225000,
        "equity": "0.4% - 1.0%",
        "experience_level": "Senior (4+ years)",
        "skills": ["Python", "Go", "Cryptography", "Security", "AWS", "PostgreSQL", "OAuth"],
        "description": "Zero-knowledge authentication and encryption infrastructure for Tier 1 banks and fintech startups. Implement cryptographic protocols and secure multi-party computation.",
        "founder_note": "Protecting over $4B in transaction volume monthly.",
        "visa_sponsorship": True,
        "culture_tags": ["Security First", "High Trust", "Fintech Scale"],
        "url": "https://www.ycombinator.com/jobs/security-engineer-vaultlayer",
        "posted_date": "2 days ago"
    },
    {
        "id": "yc-job-012",
        "title": "Lead Mobile Engineer (React Native & iOS)",
        "company": "Pulse Health",
        "company_url": "https://www.ycombinator.com/companies/pulse-health",
        "batch": "YC S23",
        "stage": "Seed ($4.2M)",
        "team_size": "10 people",
        "location": "Austin, TX",
        "work_type": "Remote OK",
        "salary_str": "$140,000 - $185,000",
        "salary_min": 140000,
        "salary_max": 185000,
        "equity": "0.5% - 1.2%",
        "experience_level": "Senior (4+ years)",
        "skills": ["React Native", "TypeScript", "iOS", "Swift", "Frontend", "GraphQL"],
        "description": "Pulse is an AI-powered longevity and health biomarker companion. Looking for a mobile engineer to build Bluetooth peripheral integrations, health kit syncing, and fluid gesture navigation.",
        "founder_note": "Featured in Apple App Store App of the Day.",
        "visa_sponsorship": False,
        "culture_tags": ["Consumer Health", "Fluid UI", "High Retention"],
        "url": "https://www.ycombinator.com/jobs/lead-mobile-pulse",
        "posted_date": "3 days ago"
    }
]
