[theme]
primaryColor = "#3f3f46"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0a0a0a"
textColor = "#ededed"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
